[bastion]
bastion.ru-central1.internal

[webservers]
web-1.ru-central1.internal
web-2.ru-central1.internal

[elasticsearch]
elasticsearch.ru-central1.internal

[zabbix]
zabbix.ru-central1.internal

[kibana]
kibana.ru-central1.internal


[all:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p ubuntu@51.250.89.40"'