---
- name: Install Zabbix Agent
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Zabbix Agent
      apt:
        name: zabbix-agent
        state: present

    - name: Configure Zabbix Server
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server='
        line: 'Server=zabbix.ru-central1.internal'

    - name: Configure Zabbix Active Server
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^ServerActive='
        line: 'ServerActive=zabbix.ru-central1.internal'

    - name: Configure Hostname
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Hostname='
        line: 'Hostname={{ inventory_hostname }}'

    - name: Restart Zabbix Agent
      service:
        name: zabbix-agent
        state: restarted
        enabled: yes